//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessAnalytics
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AccessUrl { get; set; }
        public string ReferrerUrl { get; set; }
        public string Operation { get; set; }
        public string PageTitle { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Agent { get; set; }
        public string Device { get; set; }
    }
}
