//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public int ActivityTypeId { get; set; }
        public string ActivityTypeName { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
