//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRole
    {
        public int RoleId { get; set; }
        public string RoleNmae { get; set; }
        public Nullable<int> State { get; set; }
        public string Permission { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
