//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRole
    {
        public int RoleId { get; set; }
        public string RoleNmae { get; set; }
        public Nullable<int> State { get; set; }
        public string Permission { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
