//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Domain { get; set; }
        public string Email { get; set; }
        public string QQ1 { get; set; }
        public string QQ2 { get; set; }
        public string QQ3 { get; set; }
        public string Address { get; set; }
        public string Company { get; set; }
        public string Weixin { get; set; }
        public string ICP { get; set; }
        public string StatisticalCode { get; set; }
    }
}
