//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandSubscriptionDetail
    {
        public int SubscriptionDetailId { get; set; }
        public int SubscriptionId { get; set; }
        public string SubscriptionType { get; set; }
        public string SubscriptionValue { get; set; }
        public System.DateTime InsertedTimestamp { get; set; }
    }
}
