//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandSubscriptionPushHistory
    {
        public int Id { get; set; }
        public int WechatUserId { get; set; }
        public string OpenId { get; set; }
        public bool IsMailSubscribed { get; set; }
        public string EmailAddress { get; set; }
        public int DemandId { get; set; }
        public string WechatStatus { get; set; }
        public string WechatExceptionMessage { get; set; }
        public string EmailStatus { get; set; }
        public string EmailExceptionMessage { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
