//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demand
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ContentStyle { get; set; }
        public string ContentText { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TimeLength { get; set; }
        public string PeopleNumber { get; set; }
        public Nullable<int> Budget { get; set; }
        public int ViewCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime InsertTime { get; set; }
        public string QQWeixin { get; set; }
        public string Email { get; set; }

        public Nullable<int> WeixinBuyFee { get; set; }
    }
}
