//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemandQuoteHistory
    {
        public int HistoryId { get; set; }
        public int QuoteId { get; set; }
        public int WeChatUserId { get; set; }
        public string Comments { get; set; }
        public bool HasRead { get; set; }
        public System.DateTime InsertedTimestamp { get; set; }
    }
}
