//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceRecord
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FinanceType { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertedTimestamp { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
    }
}
