//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shtsEntities : DbContext
    {
        public shtsEntities()
            : base("name=shtsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessAnalytics> AccessAnalytics { get; set; }
        public DbSet<Activity> Activity { get; set; }
        public DbSet<ActivityType> ActivityType { get; set; }
        public DbSet<Actor> Actor { get; set; }
        public DbSet<ActorType> ActorType { get; set; }
        public DbSet<AdminRole> AdminRole { get; set; }
        public DbSet<AdminUser> AdminUser { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<Config> Config { get; set; }
        public DbSet<Demand> Demand { get; set; }
        public DbSet<DemandCategory> DemandCategory { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<EquipType> EquipType { get; set; }
        public DbSet<Facility> Facility { get; set; }
        public DbSet<GuestBook> GuestBook { get; set; }
        public DbSet<Image> Image { get; set; }
        public DbSet<Other> Other { get; set; }
        public DbSet<OtherType> OtherType { get; set; }
        public DbSet<PublicConfig> PublicConfig { get; set; }
        public DbSet<Resource> Resource { get; set; }
        public DbSet<ShortMessage> ShortMessage { get; set; }
        public DbSet<SinglePage> SinglePage { get; set; }
        public DbSet<Space> Space { get; set; }
        public DbSet<SpaceFacility> SpaceFacility { get; set; }
        public DbSet<SpaceFeature> SpaceFeature { get; set; }
        public DbSet<SpacePeople> SpacePeople { get; set; }
        public DbSet<SpaceSize> SpaceSize { get; set; }
        public DbSet<SpaceType> SpaceType { get; set; }
        public DbSet<Test> Test { get; set; }
        public DbSet<Trade> Trade { get; set; }
        public DbSet<TradeHistory> TradeHistory { get; set; }
        public DbSet<TradeOrder> TradeOrder { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<UserVip> UserVip { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<UserBankInfo> UserBankInfo { get; set; }
    }
}
