//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglePage
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string EntityType { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string ContentStyle { get; set; }
        public string ContentText { get; set; }
        public string ImageUrl { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
