//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglePage
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string EntityType { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string ContentStyle { get; set; }
        public string ContentText { get; set; }
        public string ImageUrl { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
