//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsRecord
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> Userid { get; set; }
        public string Mobile { get; set; }
        public string Ip { get; set; }
        public Nullable<byte> Hascheck { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string TplId { get; set; }
        public string TypeName { get; set; }
        public string Value { get; set; }
        public System.DateTime AddTime { get; set; }
    }
}
