//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Space
    {
        public int Id { get; set; }
        public int ResourceId { get; set; }
        public int SpaceTypeId { get; set; }
        public int SpaceFeatureValue { get; set; }
        public int SpaceFacilityValue { get; set; }
        public int SpaceSizeId { get; set; }
        public int SpacePeopleId { get; set; }
        public int SpaceTreat { get; set; }
    }
}
