//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int PKG_PSID { get; set; }
        public int ProviderID { get; set; }
        public int BrandID { get; set; }
        public string ProviderName { get; set; }
        public string BrandName { get; set; }
        public string ProviderPrefix { get; set; }
        public string BrandPrefix { get; set; }
        public string ProviderDesc { get; set; }
        public string ProviderLogo { get; set; }
        public string BrandLogo { get; set; }
        public int ProviderCity { get; set; }
        public int DataStatus { get; set; }
        public System.DateTime DataChange_CreateTime { get; set; }
        public System.DateTime DataChange_Lasttime { get; set; }
    }
}
