//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeHistory
    {
        public int HistoryId { get; set; }
        public string HistorySubject { get; set; }
        public string HistoryBody { get; set; }
        public int TradeId { get; set; }
        public int UserId { get; set; }
        public bool IsAdminUpdate { get; set; }
        public string UserName { get; set; }
        public int TradeState { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
