//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int TradeId { get; set; }
        public int UserId { get; set; }
        public string UserQQ { get; set; }
        public string UserCellPhone { get; set; }
        public string UserEmail { get; set; }
        public string UserBankInfo { get; set; }
        public string UserAddress { get; set; }
        public int SellerId { get; set; }
        public int BuyerId { get; set; }
        public decimal TradeAmount { get; set; }
        public string TradeSubject { get; set; }
        public string TradeBody { get; set; }
        public int Payer { get; set; }
        public decimal PayCommission { get; set; }
        public double PayCommissionPercent { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public int State { get; set; }
        public decimal BuyerPay { get; set; }
        public decimal SellerGet { get; set; }
        public int ViewCount { get; set; }
        public string ResourceUrl { get; set; }
        public bool IsBuyerPaid { get; set; }
        public string TradeOrderId { get; set; }
    }
}
