//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeOrder
    {
        public string OrderId { get; set; }
        public decimal Amount { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime LastUpdatedTime { get; set; }
        public int State { get; set; }
        public string ResourceUrl { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> ResourceId { get; set; }
    }
}
