//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeHistory
    {
        public int HistoryId { get; set; }
        public string HistorySubject { get; set; }
        public string HistoryBody { get; set; }
        public int TradeId { get; set; }
        public int UserId { get; set; }
        public bool IsAdminUpdate { get; set; }
        public string UserName { get; set; }
        public int TradeState { get; set; }
        public System.DateTime CreatedTime { get; set; }
    }
}
