//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Witbird.SHTS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string EncryptedPassword { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Adress { get; set; }
        public string LocationId { get; set; }
        public string Cellphone { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string UCard { get; set; }
        public string SiteUrl { get; set; }
        public string LoginIdentiy { get; set; }
        public string IdentiyImg { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Vip { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<int> State { get; set; }
    }
}
